version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=${SALES_DATABASE_NAME}
      - DATABASE_USER=${SALES_DATABASE_USER}
      - DATABASE_PASSWORD=${SALES_DATABASE_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    depends_on:
      - db
    volumes:
      - .:/code
    networks:
      - app-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${SALES_DATABASE_NAME}
      POSTGRES_USER: ${SALES_DATABASE_USER}
      POSTGRES_PASSWORD: ${SALES_DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
