# Generated by Django 5.0.7 on 2024-08-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msgconv", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Processes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid_field",
                    models.CharField(
                        default="<function uuid4 at 0x102b5b880>",
                        editable=False,
                        max_length=36,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
